all: clean create copy

clean:
	rm -rf /home/cellarstone/go/src/github.com/lukaskellerstein/GolangTrainingProjects/14_Testing/00_Testing/01_Simple/

create:
	mkdir -p /home/cellarstone/go/src/github.com/lukaskellerstein/GolangTrainingProjects/14_Testing/00_Testing/01_Simple

copy:
	cp -R . /home/cellarstone/go/src/github.com/lukaskellerstein/GolangTrainingProjects/14_Testing/00_Testing/01_Simple/